project:
  type: website

website:
  title: "Autocorrelated Sampling in Cognition"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - organizers.qmd
      - schedule.qmd
      - materials.qmd
      - href: requirements.qmd
        text: Prerequisites

format:
  html:
    theme: journal
    css: styles.css
    toc: false
    # include-before-body: _in-progress.qmd
    bibliography: references.bib
    csl: ./apa.csl


